{
  "sksl": {
    "entrypoint": "test5_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float iTime;\nuniform shader iChannel0;\nuniform half2 iChannel0_size;\n\nvec4 fragColor;\n\nvec3 iResolution;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_mainImage(inout vec4 fragColor_1, vec2 fragCoord)\n{\n    vec2 uv = vec2(-1.0) + ((fragCoord * 2.0) / iResolution.xy);\n    float time = iTime * 1.0;\n    vec3 color = vec3(0.0);\n    for (float i = 0.0; i < 9.0; i += 1.0)\n    {\n        float freq = iChannel0.eval(iChannel0_size * ( vec2(i / 8.0, 0.0))).x * 7.0;\n        vec2 p = vec2(uv);\n        p.x += ((i * 0.039999999105930328369140625) + (freq * 0.02999999932944774627685546875));\n        p.y += ((((sin((p.x * 10.0) + time) * cos(p.x * 2.0)) * freq) * 0.20000000298023223876953125) * ((i + 1.0) / 8.0));\n        float intensity = abs(0.00999999977648258209228515625 / p.y) * clamp(freq, 0.3499999940395355224609375, 2.0);\n        color += (vec3((1.0 * intensity) * (i / 5.0), 0.5 * intensity, 1.75 * intensity) * 0.375);\n    }\n    fragColor_1 = vec4(color, 1.0);\n}\n\nvoid FLT_main()\n{\n    iResolution = vec3(uResolution.x, uResolution.y, 0.0);\n    vec2 param_1 = FLT_flutter_local_FlutterFragCoord();\n    vec4 param;\n    FLT_flutter_local_mainImage(param, param_1);\n    fragColor = param;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "iChannel0",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}