{
  "sksl": {
    "entrypoint": "test4_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float iTime;\nuniform shader iChannel0;\nuniform half2 iChannel0_size;\n\nvec4 fragColor;\n\nvec3 COL1;\nvec3 COL2;\nvec3 iResolution;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_mainImage(out vec4 fragColor_1, vec2 fragCoord)\n{\n    vec2 uv = fragCoord / iResolution.xy;\n    float grid = float(mod(floor(uv.x * 500.0), 14.0) < 0.5);\n    grid += float(mod(floor(uv.y * 200.0), 11.0) < 0.5);\n    grid = float(grid > 0.5);\n    vec2 uvn = (uv * 2.0) - vec2(1.0);\n    grid *= (1.0 - clamp(0.0, 1.0, pow(length(uvn), 1.2000000476837158203125)));\n    float wa = iChannel0.eval(iChannel0_size * ( vec2(uv.x, 0.75))).x;\n    float i = pow(1.0 - abs(uv.y - wa), 20.0);\n    vec3 col = (vec3(0.0, 0.4000000059604644775390625, 0.0) * grid) + (vec3(i) * mix(COL1, COL2, vec3(i)));\n    fragColor_1 = vec4(col, 0.699999988079071044921875);\n}\n\nvoid FLT_main()\n{\n    COL1 = vec3(0.60000002384185791015625, 0.0, 0.0);\n    COL2 = vec3(0.800000011920928955078125, 0.0, 0.89999997615814208984375);\n    iResolution = vec3(uResolution.x, uResolution.y, 0.0);\n    vec2 param_1 = FLT_flutter_local_FlutterFragCoord() + vec2(iTime / 1000000000.0);\n    vec4 param;\n    FLT_flutter_local_mainImage(param, param_1);\n    fragColor = param;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "iChannel0",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}