{
  "sksl": {
    "entrypoint": "test1_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform float iTime;\nuniform shader iChannel0;\nuniform half2 iChannel0_size;\n\nvec4 fragColor;\n\nvec3 iResolution;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_flutter_local_mainImage(out vec4 fragColor_1, vec2 fragCoord)\n{\n    vec2 uv = fragCoord / iResolution.xy;\n    uv = vec2(uv.x, 1.0 - uv.y);\n    vec2 p;\n    p.x = floor(uv.x * 30.0) / 30.0;\n    p.y = floor(uv.y * 40.0) / 40.0;\n    float fft = iChannel0.eval(iChannel0_size * ( vec2(p.x, 0.25))).x;\n    vec3 color = mix(vec3(0.0, 2.0, 0.0), vec3(2.0, 0.0, 0.0), vec3(sqrt(uv.y)));\n    float mask = (p.y < fft) ? 1.0 : 0.100000001490116119384765625;\n    vec2 d = fract((uv - p) * vec2(30.0, 40.0)) - vec2(0.5);\n    float led = smoothstep(0.5, 0.3499999940395355224609375, abs(d.x)) * smoothstep(0.5, 0.3499999940395355224609375, abs(d.y));\n    vec3 ledColor = (color * led) * mask;\n    fragColor_1 = vec4(ledColor, 1.0);\n}\n\nvoid FLT_main()\n{\n    iResolution = vec3(uResolution.x, uResolution.y, 0.0);\n    vec2 param_1 = FLT_flutter_local_FlutterFragCoord() - vec2(iTime / 9999999.0);\n    vec4 param;\n    FLT_flutter_local_mainImage(param, param_1);\n    fragColor = param;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "iChannel0",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "iTime",
        "rows": 1,
        "type": 10
      }
    ]
  }
}